server.port=${PORT:8082}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/resumeiq}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:ResumeIQLocalDevelopmentSecretChangeForProduction}
jwt.expiration=86400000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

app.upload.profile-dir=${PROFILE_UPLOAD_DIR:uploads/profile-images}
app.backend-base-url=${BACKEND_BASE_URL:http://localhost:8082}

logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO